### ISSUE TITLE
error loading properties

### ISSUE THREAD

**Issue by wisechengyi** [gradle/ge-export#1]
Just following the readme and got the following:

```
$ ./gradlew run -Dserver=https://ge.twitter.biz -Dhours=24 -DcreateDb
:compileJava UP-TO-DATE
:processResources
:classes
:run
14:35:29,391 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:35:29,391 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:35:29,391 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/yic/workspace/ge-export/build/resources/main/logback.xml]
14:35:29,452 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:35:29,452 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:35:29,459 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:35:29,509 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
14:35:29,509 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
14:35:29,509 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
14:35:29,509 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
14:35:29,511 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
14:35:29,512 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:35:29,513 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [export.log]
14:35:29,515 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.base22] to TRACE
14:35:29,515 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
14:35:29,515 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
14:35:29,515 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:35:29,515 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:35:29,515 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:35:29,516 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@de0a01f - Registering current configuration as safe fallback point

14:35:29.826 [main] ERROR com.gradle.exportapi.Application - Export failed 
org.knowm.yank.exceptions.PropertiesFileNotFoundException: ERROR LOADING PROPERTIES FROM CLASSPATH >POSTGRES.properties< !!!
        at org.knowm.yank.PropertiesUtils.getPropertiesFromClasspath(PropertiesUtils.java:61)
        at com.gradle.exportapi.Application.main(Application.java:44)
Caused by: java.lang.NullPointerException: null
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at org.knowm.yank.PropertiesUtils.getPropertiesFromClasspath(PropertiesUtils.java:59)
        ... 1 common frames omitted
```

Here is the dummy changes I made, and looks like it has not got to the point of authentication yet. 
```
$ git diff
diff --git a/src/main/resources/POSTGRES.properties.template b/src/main/resources/POSTGRES.properties.template
index 0f735a9..4e44898 100644
--- a/src/main/resources/POSTGRES.properties.template
+++ b/src/main/resources/POSTGRES.properties.template
@@ -1,4 +1,4 @@
 jdbcUrl=jdbc:postgresql://localhost:5432/postgres
-username=
-password=
-maximumPoolSize=5
\ No newline at end of file
+username=yi
+password=123
+maximumPoolSize=5
```

**Comment by w25r** [comment]
You need to actually rename `POSTGRES.properties.template` to `POSTGRES.properties`  It looks like you've only changed values in place.  

However, we can certainly make that error message better.

**Comment by w25r** [comment]
Actually, the error message is rather descriptive.  At first glance, I only saw the NPE, but the actual exception states
```
org.knowm.yank.exceptions.PropertiesFileNotFoundException: ERROR LOADING PROPERTIES FROM CLASSPATH >POSTGRES.properties< !!!
``` 
which is accurate if I'm reading your `git diff` correctly

**Comment by wisechengyi** [comment]
```
$ pwd
/Users/yic/workspace/ge-export
$ 
$ cat POSTGRES.properties 
jdbcUrl=jdbc:postgresql://localhost:5432/postgres
username=yi
password=123
maximumPoolSize=5
[tw-mbp-yic ge-export (master)]$ ./gradlew run -Dserver=https://ge.twitter.biz -Dhours=24 -DcreateDb
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
14:46:03,841 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:46:03,841 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:46:03,841 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/yic/workspace/ge-export/build/resources/main/logback.xml]
14:46:03,895 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:46:03,895 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:46:03,901 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:46:03,947 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
14:46:03,947 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
14:46:03,947 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
14:46:03,947 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
14:46:03,949 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
14:46:03,950 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:46:03,951 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [export.log]
14:46:03,952 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.base22] to TRACE
14:46:03,952 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
14:46:03,952 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
14:46:03,953 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:46:03,953 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:46:03,953 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:46:03,953 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@de0a01f - Registering current configuration as safe fallback point

14:46:04.189 [main] ERROR com.gradle.exportapi.Application - Export failed 
org.knowm.yank.exceptions.PropertiesFileNotFoundException: ERROR LOADING PROPERTIES FROM CLASSPATH >POSTGRES.properties< !!!
        at org.knowm.yank.PropertiesUtils.getPropertiesFromClasspath(PropertiesUtils.java:61)
        at com.gradle.exportapi.Application.main(Application.java:44)
Caused by: java.lang.NullPointerException: null
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at org.knowm.yank.PropertiesUtils.getPropertiesFromClasspath(PropertiesUtils.java:59)
        ... 1 common frames omitted

BUILD SUCCESSFUL

Total time: 1.594 secs

```

having the postgres property file in the same dir does not seem to help

**Comment by w25r** [comment]
It should be in `src/main/resources` so that Gradle throws it on the Java classpath.  So the file should be renamed in place.

**Comment by wisechengyi** [comment]
ah i see. sorry misread that.

that said, do you think it would be more straight forward to only have POSTGRES.properties and no .template in that dir? and change the readme accordingly.

**Comment by w25r** [comment]
It shouldn't have one by default, so that the user is alerted that one hasn't been created.  But I'll clear up the documentation and self-document the template so it's more clear.

**Comment by wisechengyi** [comment]
Thanks.

Another thing to clarify:
1. Is `POSTGRES.properties` specifying the destination db? e.g. my local db if I want to copy the data from the server.
2. and the command line options -Dserver -Dbasic_auth for the source db? e.g. the gradle enterprise server db

**Comment by wisechengyi** [comment]
How was the postgres db configured at the beginning in terms of credentials? no mention from https://docs.gradle.com/enterprise/admin/current/#airgapped

I checked that the postgres container is running
```
$ sudo docker ps
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                                               NAMES
596625a65335        replicated/statsd-graphite:0.1.1                    "/usr/bin/supervis..."   4 days ago          Up 4 days           0.0.0.0:8125->8125/udp, 0.0.0.0:9900->2443/tcp      replicated-statsd
896becf2e39e        172.16.153.126:9874/gradle-build-cache-image:6782   "/opt/build-cache-..."   4 days ago          Up 4 days           172.17.0.1:8081->8081/tcp                           gradle-build-cache
ba65a5624595        172.16.153.126:9874/gradle-server-image:6782        "/opt/scans-server..."   4 days ago          Up 4 days           172.17.0.1:8080->8080/tcp                           gradle-server
2f9cf6049d3f        172.16.153.126:9874/gradle-proxy-image:6782         "/usr/bin/supervisord"   4 days ago          Up 4 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp            gradle-proxy
c266cc350d0e        172.16.153.126:9874/gradle-database-image:6782      "/usr/bin/supervisord"   4 days ago          Up 4 days           172.17.0.1:5432->5432/tcp                           gradle-database
d6c45668acdd        quay.io/replicated/replicated-operator:current      "/usr/bin/replicat..."   12 days ago         Up 12 days                                                              replicated-operator
6275aef85f6c        quay.io/replicated/replicated-ui:current            "/usr/bin/replicat..."   12 days ago         Up 12 days          0.0.0.0:8800->8800/tcp                              replicated-ui
0bc378288228        quay.io/replicated/replicated:current               "entrypoint.sh -d"       12 days ago         Up 12 days          0.0.0.0:9874-9879->9874-9879/tcp                    replicated
4705b7df7c90        premkit/premkit:1.0.0                               "/usr/bin/premkit ..."   2 weeks ago         Up 2 weeks          80/tcp, 443/tcp, 2080/tcp, 0.0.0.0:9880->2443/tcp   replicated-premkit
```

then try to log into it, but got the following error
```
$ psql -h localhost -U yi -W
Password for user yi: 
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

**Comment by wisechengyi** [comment]
so 2 issues here:
1. gradle-database does not listen on the public interface. is there a quick way to change that? where are the docker files for this container stored, and is it safe to tweak it myself?
```
172.17.0.1:5432->5432/tcp                           gradle-database
```
2. the username/password to the db is unknown. anywhere I can find it in some configuration file?

**Comment by w25r** [comment]
The ge-export tool is meant to export to an external database, not the database that Gradle Enterprise is using.  I can add some notes to clarify that (perhaps a prerequisite section).

**Comment by wisechengyi** [comment]
Yes, that'd be good. I was able to figure out POSTGRES.properties is for the destination db. 

Feel free to close this one out when it is clarified.
