### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by wisechengyi** [gradle/ge-export#7]
Got the following error after running for a few minutes, so probably a memory leak/forgetting to release resources somewhere.

```
14:04:37.358 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : s5rbs54mtdqwu
14:04:54.127 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : iixvsdba4r4ve
Could not allocate an instance of [B (size = 8176 bytes) due to: GC overhead limit exceeded
14:05:20.603 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Error streaming build events of build iixvsdba4r4ve, resuming from event id6788...
14:05:20.604 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : iixvsdba4r4ve
14:05:26.812 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : gfymezr6enasi
14:05:26.940 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : fyxlgea3ihqge
Could not allocate an instance of [B (size = 4096 bytes) due to: GC overhead limit exceeded
14:06:00.837 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Error streaming build events of build fyxlgea3ihqge, resuming from event id6139...
14:06:00.838 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : fyxlgea3ihqge
Could not allocate an instance of com/fasterxml/jackson/core/json/JsonReadContext (size = 48 bytes) due to: GC overhead limit exceeded
14:06:15.453 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Error streaming build events of build fyxlgea3ihqge, resuming from event id7887...
14:06:15.453 [rxnetty-nio-eventloop-1-1] INFO  com.gradle.exportapi.Application - Streaming events for : fyxlgea3ihqge
14:06:15.820 [rxnetty-nio-eventloop-1-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.reactivex.netty.client.ClientConnectionToChannelBridge.handlerRemoved() has thrown an exception.
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:636)
        at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:883)
        at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:849)
        at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:841)
        at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1316)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:190)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:176)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:826)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:752)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:133)
        at io.reactivex.netty.protocol.http.sse.ServerSentEvent.release(ServerSentEvent.java:230)
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
        at io.reactivex.netty.channel.BackpressureManagingHandler.handlerRemoved(BackpressureManagingHandler.java:108)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:631)
        ... 15 common frames omitted
<=========----> 75% EXECUTING
```

**Comment by w25r** [comment]
It could be a memory leak, or could be you need to run with more memory.  Have you tried increasing the memory?  If it simply takes longer to error, then it is certainly a memory leak (or memory growth).

**Comment by wisechengyi** [comment]
closed due to no longer needed
